networks:
  pontifex:
    driver: bridge

services:
  proxy:
    container_name: pontifex-proxy
    image: traefik:v3.6.7
    labels:
      traefik.http.routers.pontifex-traefik.rule: "Host(`traefik.pontifex.localhost`)"
      traefik.http.routers.pontifex-traefik.tls: true
      traefik.http.routers.pontifex-traefik.service: api@internal
      traefik.http.routers.pontifex-traefik.entrypoints: websecure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.traefik/certs:/etc/certs:ro
      - ./.traefik/config:/config
    networks:
      - pontifex
    ports:
      - "8080:80"
      - "8443:443"
      - "8283:8080"
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--providers.file.directory=/config"
    depends_on:
      - api
      - ui

  gremlin:
    container_name: pontifex-gremlin
    image: tinkerpop/gremlin-server:3.7.3
    ports:
      - "8182:8182"
    volumes:
      - gremlin_data:/opt/gremlin-server/data
      - ./gremlin/conf:/opt/gremlin-server/conf
    networks:
      - pontifex

  mail:
    container_name: pontifex-mail
    image: axllent/mailpit:latest
    labels:
      traefik.http.routers.pontifex-mail.rule: "Host(`mail.pontifex.localhost`)"
      traefik.http.routers.pontifex-mail.tls: true
      traefik.http.routers.pontifex-mail.entrypoints: websecure
      traefik.http.services.pontifex-mail-backend.loadbalancer.server.port: 8025
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - pontifex

  api:
    container_name: pontifex-api
    build:
      context: ./api
      target: development
    labels:
      traefik.http.routers.pontifex-api.rule: "Host(`api.pontifex.localhost`)"
      traefik.http.routers.pontifex-api.tls: true
      traefik.http.routers.pontifex-api.entrypoints: websecure
      traefik.http.services.pontifex-api-backend.loadbalancer.server.port: 3001
    env_file: ./api/.env
    environment:
      PONTIFEX_DATABASE_ENDPOINT: ws://gremlin:8182/gremlin
      PONTIFEX_SMTP_HOST: mail
      PONTIFEX_SMTP_PORT: 1025
      PONTIFEX_SMTP_FROM: pontifex@pontifex.localhost
      PORT: 3001
    volumes:
      - ./api/src:/app/src:cached
      - ./api/test:/app/test:cached
      - ./api/nest-cli.json:/app/nest-cli.json
      - ./api/tsconfig.json:/app/tsconfig.json
      - ./api/tsconfig.build.json:/app/tsconfig.build.json
      - ./api/webpack-hmr.config.js:/app/webpack-hmr.config.js
    networks:
      - pontifex
    depends_on:
      - gremlin
      - mail

  ui:
    container_name: pontifex-ui
    build:
      context: ./ui
      target: development
    labels:
      traefik.http.routers.pontifex-ui.rule: "Host(`app.pontifex.localhost`)"
      traefik.http.routers.pontifex-ui.tls: true
      traefik.http.routers.pontifex-ui.entrypoints: websecure
      traefik.http.services.pontifex-ui-backend.loadbalancer.server.port: 3000
    env_file: ./ui/.env
    environment:
      NEXT_PUBLIC_APIM_URL: http://pontifex-api:3001/api
    volumes:
      - ./ui/components:/app/components:cached
      - ./ui/pages:/app/pages:cached
      - ./ui/public:/app/public:cached
      - ./ui/styles:/app/styles:cached
      - ./ui/hooks:/app/hooks:cached
      - ./ui/utils:/app/utils:cached
      - ./ui/models:/app/models:cached
      - ./ui/interfaces:/app/interfaces:cached
      - ./ui/strings:/app/strings:cached
      - ./ui/config:/app/config:cached
      - ./ui/theme:/app/theme:cached
      - ./ui/images:/app/images:cached
      - ./ui/resources:/app/resources:cached
      - ./ui/next.config.js:/app/next.config.js
      - ./ui/server-preload.js:/app/server-preload.js
      - ./ui/tsconfig.json:/app/tsconfig.json
    networks:
      - pontifex
    depends_on:
      - api

volumes:
  gremlin_data:
